name: Sync Stars with stargazed
on:
  schedule:
    # cron 时间：UTC时间，下面是【每天早上8点UTC ≈ 北京时间16点】执行
    - cron: '0 8 * * *'
  workflow_dispatch: # 手动触发按钮，可以随时点Run workflow立刻同步

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install stargazed
        run: npm install -g stargazed

      - name: Run stargazed generate awesome readme
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # 替换为你的github用户名
        run: stargazed -u 你的github用户名

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🤖 Auto update stars list by stargazed" || echo "No changes to commit"
          git push
